"use client"

import { useState, useEffect } from "react"
import { createClient } from "@/lib/supabase/client"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Alert, AlertDescription } from "@/components/ui/alert"
import { Badge } from "@/components/ui/badge"
import { FileText, Download, Calendar, BarChart3, Loader2, Plus } from "lucide-react"
import { formatDate } from "@/lib/date-utils"

interface Report {
  id: string
  title: string
  report_type: string
  generated_at: string
  status: string
  farmer_id: string
}

interface ReportsGeneratorProps {
  farmerId: string
}

export function ReportsGenerator({ farmerId }: ReportsGeneratorProps) {
  const [reports, setReports] = useState<Report[]>([])
  const [isLoading, setIsLoading] = useState(true)
  const [isDialogOpen, setIsDialogOpen] = useState(false)
  const [isGenerating, setIsGenerating] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const [formData, setFormData] = useState({
    reportType: "",
    startDate: "",
    endDate: "",
    title: ""
  })

  useEffect(() => {
    const fetchReports = async () => {
      // Mock reports data
      const mockReports: Report[] = [
        {
          id: "1",
          title: "Health Summary Report - January 2025",
          report_type: "health_summary",
          generated_at: "2025-01-08T10:30:00Z",
          status: "completed",
          farmer_id: farmerId
        },
        {
          id: "2",
          title: "Inventory Report - January 2025",
          report_type: "inventory_report",
          generated_at: "2025-01-07T14:20:00Z",
          status: "completed",
          farmer_id: farmerId
        },
        {
          id: "3",
          title: "Biosecurity Assessment Report",
          report_type: "biosecurity_assessment",
          generated_at: "2025-01-06T09:15:00Z",
          status: "completed",
          farmer_id: farmerId
        },
        {
          id: "4",
          title: "Risk Analysis Report - Q1 2025",
          report_type: "risk_analysis",
          generated_at: "2025-01-05T16:45:00Z",
          status: "completed",
          farmer_id: farmerId
        }
      ]

      // Simulate API call
      setTimeout(() => {
        setReports(mockReports)
        setIsLoading(false)
      }, 1000)
    }

    fetchReports()
  }, [farmerId])

  const reportTypes = [
    { id: "health_summary", name: "Health Summary Report", description: "Overview of livestock health status" },
    { id: "inventory_report", name: "Inventory Report", description: "Complete livestock inventory details" },
    { id: "biosecurity_assessment", name: "Biosecurity Assessment", description: "Farm biosecurity evaluation" },
    { id: "risk_analysis", name: "Risk Analysis Report", description: "Comprehensive risk assessment" },
    { id: "performance_metrics", name: "Performance Metrics", description: "Farm performance indicators" }
  ]

  const generatePDFReport = (reportType: string, title: string) => {
    // Create a simple PDF-like content
    const reportContent = `
BIOSECURITY PORTAL REPORT
${title}
Generated: ${formatDate(new Date())}

REPORT SUMMARY:
${getReportContent(reportType)}

FARM DATA:
- Total Livestock: 213 animals
- Healthy Animals: 202 (94.8%)
- Sick Animals: 11 (5.2%)
- Recent Health Records: 15 entries
- Active Alerts: 3

RECOMMENDATIONS:
- Continue regular health monitoring
- Schedule vaccination program
- Review biosecurity protocols
- Monitor feed quality

---
Generated by Digital Biosecurity Portal
    `.trim()

    // Create and download file
    const blob = new Blob([reportContent], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${title.replace(/[^a-zA-Z0-9]/g, '_')}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)

    // Voice feedback
    if ('speechSynthesis' in window) {
      const utterance = new SpeechSynthesisUtterance(`Report downloaded successfully`)
      utterance.rate = 0.8
      speechSynthesis.speak(utterance)
    }
  }

  const getReportContent = (reportType: string) => {
    switch (reportType) {
      case "health_summary":
        return "This report provides a comprehensive overview of your livestock health status, including vaccination records, treatment history, and health trends."
      case "inventory_report":
        return "Complete inventory listing with animal details, health status, and management information for all livestock on your farm."
      case "biosecurity_assessment":
        return "Evaluation of your farm's biosecurity measures, identifying strengths and areas for improvement in disease prevention protocols."
      case "risk_analysis":
        return "Comprehensive risk assessment covering disease outbreaks, environmental factors, and management practices affecting livestock health."
      case "performance_metrics":
        return "Key performance indicators including growth rates, feed conversion ratios, and productivity metrics for your livestock operation."
      default:
        return "General farm report with key metrics and recommendations."
    }
  }

  const handleGenerateReport = async (e: React.FormEvent) => {
    e.preventDefault()
    setIsGenerating(true)
    setError(null)

    try {
      const reportTitle = formData.title || `${reportTypes.find(t => t.id === formData.reportType)?.name} - ${formatDate(new Date())}`
      
      // Simulate report generation
      await new Promise(resolve => setTimeout(resolve, 2000))
      
      // Add new report to list
      const newReport: Report = {
        id: Date.now().toString(),
        title: reportTitle,
        report_type: formData.reportType,
        generated_at: new Date().toISOString(),
        status: "completed",
        farmer_id: farmerId
      }

      setReports(prev => [newReport, ...prev])

      // Voice feedback
      if ('speechSynthesis' in window) {
        const utterance = new SpeechSynthesisUtterance(`Report generated successfully`)
        utterance.rate = 0.8
        speechSynthesis.speak(utterance)
      }

      // Reset form
      setFormData({
        reportType: "",
        startDate: "",
        endDate: "",
        title: ""
      })
      
      setIsDialogOpen(false)
    } catch (error: any) {
      setError("Failed to generate report")
    } finally {
      setIsGenerating(false)
    }
  }

  const getStatusBadge = (status: string) => {
    const statusConfig = {
      generating: { color: "bg-yellow-100 text-yellow-700", label: "Generating" },
      completed: { color: "bg-green-100 text-green-700", label: "Completed" },
      failed: { color: "bg-red-100 text-red-700", label: "Failed" }
    }
    
    const config = statusConfig[status as keyof typeof statusConfig] || statusConfig.completed
    return <Badge className={config.color}>{config.label}</Badge>
  }

  const getReportTypeIcon = (type: string) => {
    switch (type) {
      case "health_summary":
        return <BarChart3 className="h-4 w-4 text-green-600" />
      case "inventory_report":
        return <FileText className="h-4 w-4 text-blue-600" />
      case "biosecurity_assessment":
        return <FileText className="h-4 w-4 text-orange-600" />
      case "risk_analysis":
        return <BarChart3 className="h-4 w-4 text-red-600" />
      case "performance_metrics":
        return <BarChart3 className="h-4 w-4 text-purple-600" />
      default:
        return <FileText className="h-4 w-4 text-gray-600" />
    }
  }

  if (isLoading) {
    return (
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <FileText className="h-5 w-5 text-primary" />
            Reports
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="space-y-3">
            {[...Array(3)].map((_, i) => (
              <div key={i} className="animate-pulse">
                <div className="h-16 bg-muted rounded-lg"></div>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>
    )
  }

  return (
    <Card>
      <CardHeader className="flex flex-row items-center justify-between">
        <CardTitle className="flex items-center gap-2">
          <FileText className="h-5 w-5 text-primary" />
          Reports
        </CardTitle>
        <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
          <DialogTrigger asChild>
            <Button size="sm" className="gap-2" data-voice-trigger="generate-report">
              <Plus className="h-4 w-4" />
              Generate Report
            </Button>
          </DialogTrigger>
          <DialogContent className="max-w-md">
            <DialogHeader>
              <DialogTitle>Generate New Report</DialogTitle>
            </DialogHeader>
            
            <form onSubmit={handleGenerateReport} className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="reportType">Report Type *</Label>
                <Select value={formData.reportType} onValueChange={(value) => setFormData({...formData, reportType: value})}>
                  <SelectTrigger>
                    <SelectValue placeholder="Select report type" />
                  </SelectTrigger>
                  <SelectContent>
                    {reportTypes.map((type) => (
                      <SelectItem key={type.id} value={type.id}>
                        <div>
                          <div className="font-medium">{type.name}</div>
                          <div className="text-xs text-muted-foreground">{type.description}</div>
                        </div>
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              <div className="space-y-2">
                <Label htmlFor="title">Report Title</Label>
                <Input
                  id="title"
                  value={formData.title}
                  onChange={(e) => setFormData({...formData, title: e.target.value})}
                  placeholder="Custom title (optional)"
                />
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="startDate">Start Date</Label>
                  <Input
                    id="startDate"
                    type="date"
                    value={formData.startDate}
                    onChange={(e) => setFormData({...formData, startDate: e.target.value})}
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="endDate">End Date</Label>
                  <Input
                    id="endDate"
                    type="date"
                    value={formData.endDate}
                    onChange={(e) => setFormData({...formData, endDate: e.target.value})}
                  />
                </div>
              </div>

              {error && (
                <Alert variant="destructive">
                  <AlertDescription>{error}</AlertDescription>
                </Alert>
              )}

              <div className="flex gap-2 pt-4">
                <Button type="button" variant="outline" onClick={() => setIsDialogOpen(false)} className="flex-1">
                  Cancel
                </Button>
                <Button type="submit" disabled={isGenerating || !formData.reportType} className="flex-1">
                  {isGenerating ? (
                    <>
                      <Loader2 className="h-4 w-4 animate-spin mr-2" />
                      Generating...
                    </>
                  ) : (
                    "Generate Report"
                  )}
                </Button>
              </div>
            </form>
          </DialogContent>
        </Dialog>
      </CardHeader>
      <CardContent>
        {reports.length === 0 ? (
          <div className="text-center py-8">
            <FileText className="h-12 w-12 text-muted-foreground mx-auto mb-4" />
            <p className="text-muted-foreground">No reports generated yet</p>
            <p className="text-sm text-muted-foreground mt-2">Generate your first report to track farm performance</p>
          </div>
        ) : (
          <div className="space-y-3">
            {reports.map((report) => (
              <div key={report.id} className="flex items-center justify-between p-3 rounded-lg border border-border">
                <div className="flex items-center gap-3">
                  <div className="bg-primary/10 p-2 rounded-lg">
                    {getReportTypeIcon(report.report_type)}
                  </div>
                  <div>
                    <h4 className="font-medium text-sm">{report.title}</h4>
                    <div className="flex items-center gap-2 mt-1">
                      <p className="text-xs text-muted-foreground">
                        {reportTypes.find(t => t.id === report.report_type)?.name || report.report_type}
                      </p>
                      <span className="text-xs text-muted-foreground">•</span>
                      <p className="text-xs text-muted-foreground">
                        {formatDate(report.generated_at)}
                      </p>
                    </div>
                  </div>
                </div>
                <div className="flex items-center gap-2">
                  {getStatusBadge(report.status)}
                  {report.status === "completed" && (
                    <Button 
                      size="sm" 
                      variant="outline" 
                      className="gap-2"
                      onClick={() => generatePDFReport(report.report_type, report.title)}
                    >
                      <Download className="h-3 w-3" />
                      Download
                    </Button>
                  )}
                </div>
              </div>
            ))}
          </div>
        )}

        {/* Sample Reports for Demo */}
        {reports.length === 0 && (
          <div className="mt-6 p-4 bg-muted/50 rounded-lg">
            <h4 className="font-medium mb-2">Available Report Types:</h4>
            <div className="space-y-2 text-sm text-muted-foreground">
              {reportTypes.map((type) => (
                <div key={type.id} className="flex items-center gap-2">
                  <FileText className="h-4 w-4 text-primary" />
                  <span>{type.name}</span>
                </div>
              ))}
            </div>
            <p className="text-xs text-muted-foreground mt-2">
              Reports will be generated based on your farm data and can be downloaded as PDF files.
            </p>
          </div>
        )}
      </CardContent>
    </Card>
  )
}
